# -*- coding: utf-8 -*-

import random
import smtplib

def roll_a_dice(min, max): #main function

    roll_again = "yes" #checking in "while"

    while roll_again == "yes" or roll_again == "y": #main loop
        print('rolling the dices...')
        print('wait for it ! .......')
        f_sum = print(random.randint(min, max))
        s_sum = print(random.randint(min, max))

        roll_again = input('wanna roll again hmm ? \n') #goto main functiom

        if (roll_again == "no" or roll_again == "n"):
            break

        sum = f_sum + s_sum #adding random numbers generated by random.radint,()
        #do not know what to do with that shit but I'll leave it for now xd

arg1 = int(input('Enter first number of range \n'))
arg2 = int(input('What next ? \n'))

if (arg1 >= 0 and arg2 >= 0 and arg1 < arg2):
    roll_a_dice(arg1, arg2)
else:
    print('co ty odpierdalasz mordo ??')

